language: node_js

node_js:
  - "0.10"
  #- "0.11.13"

addons:
  postgresql: "9.3"

before_install:
 - createdb template_postgis
 - psql -c "CREATE EXTENSION postgis" template_postgis
 # upgrade libstdc++ to support C++11
 - if [ $(uname -s) == "Linux" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt-get update -q && sudo apt-get install -y libstdc++6; fi

install:
- npm install --fallback-to-build=false
- python test/check_shared_libs.py node_modules/

before_script:
 - npm ls

script:
 - npm test
